apiVersion: apps/v1
kind: Deployment
metadata:
  name: champion-league
  labels:
    run: champion-league
spec:
  replicas: 2
  selector:
    matchLabels:
      run: champion-league
  template:
    metadata:
      labels:
        run: champion-league
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      # - image: cafaray/champions-league:v7.2.3
      - image: cafaray/champions-league:v7.2.3
        name: champion-league
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - name: firebase-secret
            mountPath: /app
            readOnly: true
        env:
          - name: PGBOUNCER_JDBC_URI
            valueFrom:
              secretKeyRef:
                name: supporter-credentials
                key: pgbouncer-jdbc-uri
          - name: PGBOUNCER_USER
            valueFrom:
              secretKeyRef:
                name: supporter-credentials
                key: user
          - name: PGBOUNCER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: supporter-credentials
                key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: firebase-secret
          secret:
            secretName: firebase-config
      securityContext:
        runAsUser: 185
        fsGroup: 185
        # runAsGroup: 185